### PR TITLE
reset entries

### LINKED ISSUE #245: bug: dat.land is displaying wrong archive data when multiple tabs are sharing
steps to reproduce (this bug is ephemeral so i can't reproduce consistently but it has happened more than once for me):

1) share a dat from cli
2) share a dat from dat.land client side webrtc
3) load up each in your dat.land dev browser

results: 
when you load up the dat.land route containing the key shared via dat.land client/webrtc connection, it either NEVER joins the swarm and fetches the data, and if it does, it (sometimes!) renders the data from the dat being shared via cli(!). WTF? sounds crazy but i have the screenshots to prove it:

screenshots:
* first shot is of the client-shared webrtc dat
* second shot is when i tried to load the client-shared webrtc dat above. It is instead showing the dat data from the third shot below. --> CRAZY.
* third shot is the dat im sharing from cli

screen shot 2016-09-09 at 5 15 46 pm

screen shot 2016-09-09 at 5 15 53 pm

screen shot 2016-09-09 at 5 15 49 pm

### PR DESCRIPTION
**Pull request by karissa**
fixes #245

### CODE REVIEW

**Comment by laurengarcia** [comment]
for posterity: bug was introduced here https://github.com/datproject/dat.land/commit/9ebaecb954a6cac75755e15c9d906257a10cc1b1

File: server/router.js [hunk 1]
```diff
@@ -45,6 +45,7 @@ router.on('/:archiveKey', {
     }, () => {
       cancelled = true
       console.log('server getArchive() timed out for key: ' + params.archiveKey)
+      state.archive.entries = []
```
Comment (karissa) [inline server/router.js]: do we still need this ?

Comment (laurengarcia) [inline server/router.js]: whoops -- i left it because it doesn't hurt, you can remove directly from master if you feel strongly bc i just merged this.
